### ISSUE TITLE
FPC fingerprint sensor

### ISSUE THREAD

**Issue by rufoa** [Loup-ROM/msm-3.18#13]
Hi Noyer, thanks for your work on this!

I'm using your 3.18.89 release with [Paranoid Android](https://forum.xda-developers.com/xiaomi-redmi-4x/development/rom-paranoid-android-7-3-0-aospa-redmi-t3696813). It works well, apart from the FPC fingerprint sensor on my 4X.

It appears my phone is trying (and failing) to use the Goodix driver instead. I do not understand why.

Here is the [dmesg output](https://github.com/bitrvmpd/msm-3.18/files/1580367/santoni.dmesg.txt).
Here is the logcat output I get. It repeats the same messages every few seconds:

```
12-21 18:51:35.084  9788  9788 D FingerGoodix: FingerPrintService is constructing
12-21 18:51:35.084  9788  9788 D FingerGoodix: FingerPrintService is initializing
12-21 18:51:35.086  9788  9788 D FingerGoodix: gxFingerPrint open succuss!
12-21 18:51:35.086  9788  9788 E FingerGoodix: start open /dev/goodix_fp.
12-21 18:51:35.086  9788  9788 D FingerGoodix: gf_enable_gpio
12-21 18:51:35.451  9788  9788 D FingerGoodix: Open device[/dev/goodix_fp] success. Handle = 4
12-21 18:51:35.451  9788  9788 D FingerGoodix: gf_ready_spiclk. g_spi_clk = 0
12-21 18:51:35.457  9788  9788 D FingerGoodix: gx_ta_start
12-21 18:51:35.546  9788  9788 D FingerGoodix: Loading goodixfp Succeed.
12-21 18:51:35.546  9788  9788 D FingerGoodix: Ta start success.
12-21 18:51:35.547  9788  9788 D FingerGoodix: open failed 
12-21 18:51:35.547  9788  9788 D FingerGoodix: fnCa_Init OTP[0-7]:0x0-0x0-0x0-0x0-0x0-0x0-0x0-0x0
12-21 18:51:35.547  9788  9788 D FingerGoodix: fnCa_Init OTP[8-15]:0x0-0x0-0x0-0x0-0x0-0x0-0x0-0x0
12-21 18:51:35.547  9788  9788 D FingerGoodix: fnCa_Init OTP[16-23]:0x0-0x0-0x0-0x0-0x0-0x0-0x0-0x0
12-21 18:51:35.547  9788  9788 D FingerGoodix: fnCa_Init OTP[24-31]:0x0-0x0-0x0-0x0-0x0-0x0-0x0-0x0
12-21 18:51:35.555  9788  9788 E FingerGoodix: ##Davy teeRet = 0 ,data[32] = aa
12-21 18:51:35.555  9788  9788 D FingerGoodix: fnCa_Init OTP[0-7]:0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa
12-21 18:51:35.555  9788  9788 D FingerGoodix: fnCa_Init OTP[8-15]:0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa
12-21 18:51:35.555  9788  9788 D FingerGoodix: fnCa_Init OTP[16-23]:0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa
12-21 18:51:35.555  9788  9788 D FingerGoodix: fnCa_Init OTP[24-31]:0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa
12-21 18:51:35.555  9788  9788 E FingerGoodix: error. This IC isn't GoodixFP
12-21 18:51:35.555  9788  9788 E FingerGoodix: fnCa_Init : -1!
12-21 18:51:35.555  9788  9788 D FingerGoodix: gx_ta_stop
12-21 18:51:35.568  9788  9788 D FingerGoodix: Unload goodixfp succeed.
12-21 18:51:35.568  9788  9788 D FingerGoodix: Ta stop success.
12-21 18:51:35.568  9788  9788 D FingerGoodix: Close netlink thread.
12-21 18:51:35.568  9788  9788 D FingerGoodix: Close device. Handle = 4
12-21 18:51:35.568  9788  9788 D FingerGoodix: gf_release_gpio,gf_release_gpio
12-21 18:51:35.568  9788  9788 D FingerGoodix: gf_release_gpio,gf_release_gpio by ioctl
12-21 18:51:35.568  9788  9788 D FingerGoodix: gf_close,Close device,gf_release_gpio
12-21 18:51:35.569  9788  9788 D FingerGoodix: Close device. Handle = 4
12-21 18:51:35.569  9788  9788 D FingerGoodix: , ret = 0
12-21 18:51:35.569  9788  9788 E FingerGoodix: Can't open fingerprint methods, error: -1
12-21 18:51:35.569  9788  9788 D FingerGoodix: getprop[persist.sys.fp.vendor] return: 6, prop: goodix
12-21 18:51:35.569  9788  9788 D FingerGoodix: getprop[persist.sys.fp.goodix] return: 1, prop: 0
12-21 18:51:35.578  9788  9788 D FingerGoodix: setprop[persist.sys.fp.goodix] to '0', return: 0
12-21 18:51:35.578  9788  9788 E FingerGoodix: fpservice init err: -1
12-21 18:51:35.578  9788  9788 E FingerGoodix: FingerPrintService is ~FpService()
12-21 18:51:35.578  9788  9788 D FingerGoodix: but finger print is busy
```

Many thanks

**Comment by bitrvmpd** [comment]
Have you tried other ROMs?. Also, please attach fdt file located in sys/firmware/fdt. 

Hey @nikesh001 check this, seems more like a DT problem than a kernel issue.

**Comment by rufoa** [comment]
I haven't tried other ROMs yet, but I will do soon

[fdt.zip](https://github.com/bitrvmpd/msm-3.18/files/1580591/fdt.zip)

**Comment by Nikesh001** [comment]
@bitrvmpd Its not DT.. I dont know why he gets this bcoz other fpc user didnt faced this issue

**Comment by bitrvmpd** [comment]
Ok, Then I will close this issue until @rufoa tests another ROM.

**Comment by rufoa** [comment]
Tested with xiaomi.eu stable - same problem

**With default xiaomi.eu kernel (3.18.31-perf-gccfe386)**
- fingerprint works
- getprop reports:
   ```
   [persist.sys.fp.goodix]: [0]
   [ro.boot.fpsensor]: [fpc]
   ```
- [fdt](https://github.com/bitrvmpd/msm-3.18/files/1583845/fdt.zip)

**With Loup kernel**
- fingerprint does not work
- getprop reports:
   ```
   [goodix.fp.miui.analyse]: [1]
   [persist.sys.fp.goodix]: [0]
   [persist.sys.fp.vendor]: [goodix]
   [ro.boot.fpsensor]: [gdx]
   ```
- [dmesg](https://github.com/bitrvmpd/msm-3.18/files/1583829/xiaomi.eu.loup.dmesg.txt)
- logcat output:
   ```
   12-23 03:06:05.770  9604  9604 D FingerGoodix: FingerPrintService is constructing
   12-23 03:06:05.770  9604  9604 D FingerGoodix: FingerPrintService is initializing
   12-23 03:06:05.772  9604  9604 D FingerGoodix: gxFingerPrint open succuss!
   12-23 03:06:05.772  9604  9604 E FingerGoodix: start open /dev/goodix_fp.
   12-23 03:06:05.772  9604  9604 D FingerGoodix: gf_enable_gpio
   12-23 03:06:06.137  9604  9604 D FingerGoodix: Open device[/dev/goodix_fp] success. Handle = 4
   12-23 03:06:06.137  9604  9604 D FingerGoodix: gf_ready_spiclk. g_spi_clk = 0
   12-23 03:06:06.143  9604  9604 D FingerGoodix: gx_ta_start
   12-23 03:06:06.143  9604  9604 E QSEECOMAPI: Error::Cannot open the file /system/etc/firmware/goodixfp.mdt errno = 2
   12-23 03:06:06.143  9604  9604 D FingerGoodix: Loading goodixfp failed: ret=-1, errno=2.
   12-23 03:06:06.236  9604  9604 D FingerGoodix: Loading goodixfp Succeed.
   12-23 03:06:06.236  9604  9604 D FingerGoodix: Ta start success.
   12-23 03:06:06.237  9604  9604 D FingerGoodix: open failed 
   12-23 03:06:06.237  9604  9604 D FingerGoodix: fnCa_Init OTP[0-7]:0x0-0x0-0x0-0x0-0x0-0x0-0x0-0x0
   12-23 03:06:06.237  9604  9604 D FingerGoodix: fnCa_Init OTP[8-15]:0x0-0x0-0x0-0x0-0x0-0x0-0x0-0x0
   12-23 03:06:06.237  9604  9604 D FingerGoodix: fnCa_Init OTP[16-23]:0x0-0x0-0x0-0x0-0x0-0x0-0x0-0x0
   12-23 03:06:06.237  9604  9604 D FingerGoodix: fnCa_Init OTP[24-31]:0x0-0x0-0x0-0x0-0x0-0x0-0x0-0x0
   12-23 03:06:06.243  9604  9604 E FingerGoodix: ##Davy teeRet = 0 ,data[32] = aa
   12-23 03:06:06.244  9604  9604 D FingerGoodix: fnCa_Init OTP[0-7]:0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa
   12-23 03:06:06.244  9604  9604 D FingerGoodix: fnCa_Init OTP[8-15]:0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa
   12-23 03:06:06.244  9604  9604 D FingerGoodix: fnCa_Init OTP[16-23]:0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa
   12-23 03:06:06.244  9604  9604 D FingerGoodix: fnCa_Init OTP[24-31]:0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa-0xaa
   12-23 03:06:06.244  9604  9604 E FingerGoodix: error. This IC isn't GoodixFP
   12-23 03:06:06.244  9604  9604 E FingerGoodix: fnCa_Init : -1!
   12-23 03:06:06.244  9604  9604 D FingerGoodix: gx_ta_stop
   12-23 03:06:06.258  9604  9604 D FingerGoodix: Unload goodixfp succeed.
   12-23 03:06:06.258  9604  9604 D FingerGoodix: Ta stop success.
   12-23 03:06:06.258  9604  9604 D FingerGoodix: Close netlink thread.
   12-23 03:06:06.258  9604  9604 D FingerGoodix: Close device. Handle = 4
   12-23 03:06:06.258  9604  9604 D FingerGoodix: gf_release_gpio,gf_release_gpio
   12-23 03:06:06.258  9604  9604 D FingerGoodix: gf_release_gpio,gf_release_gpio by ioctl
   12-23 03:06:06.258  9604  9604 D FingerGoodix: gf_close,Close device,gf_release_gpio
   12-23 03:06:06.259  9604  9604 D FingerGoodix: Close device. Handle = 4
   12-23 03:06:06.259  9604  9604 D FingerGoodix: , ret = 0
   12-23 03:06:06.259  9604  9604 E FingerGoodix: Can't open fingerprint methods, error: -1
   12-23 03:06:06.259  9604  9604 D FingerGoodix: getprop[persist.sys.fp.vendor] return: 6, prop: goodix
   12-23 03:06:06.259  9604  9604 D FingerGoodix: getprop[persist.sys.fp.goodix] return: 1, prop: 0
   12-23 03:06:06.273  9604  9604 D FingerGoodix: setprop[persist.sys.fp.goodix] to '0', return: 0
   12-23 03:06:06.273  9604  9604 E FingerGoodix: fpservice init err: -1
   12-23 03:06:06.273  9604  9604 E FingerGoodix: FingerPrintService is ~FpService()
   12-23 03:06:06.273  9604  9604 D FingerGoodix: but finger print is busy
   ```

**Comment by bitrvmpd** [comment]
OK, thanks for the logs. Will check this after the holidays.

**Comment by rufoa** [comment]
Thanks! Have a good break and let me know if I can help in any way.

**Comment by rufoa** [comment]
I have tried [Clarity kernel](https://github.com/ryan-andri/android_kernel_santoni/) (which is also based on CAF) and the fingerprint sensor works for me!

The only difference I can see, at the moment, is that Clarity has an updated FPC driver with some changes by Xiaomi:
- [original version in Loup](https://github.com/bitrvmpd/msm-3.18/blob/81b32391bd01d0a438791ddca3406ce45e844d51/drivers/input/fingerprint/fpc/fpc1020_tee.c)
- [newer version in Clarity](https://github.com/ryan-andri/android_kernel_santoni/blob/bc0a7d69aecb1f9d164905727897486491f718a7/drivers/fingerprint/fpc/fpc1020_tee.c)

I wonder if this could be the cause? I'm not sure, because I thought the wrong (goodix) driver was being loaded before this.

**Comment by bitrvmpd** [comment]
Woah, thank you so much!. Will test that driver tonight (i was using the one from land instead of markw, as i remember).  Expect an update ~~tomorrow~~ today!

**Comment by bitrvmpd** [comment]
[New release](https://github.com/bitrvmpd/msm-3.18/releases/tag/3.18.90) is up!, including fixes.

**Comment by rufoa** [comment]
Bad news unfortunately - new kernel is still trying to use the goodix driver. The problem must have been something else

**Comment by bitrvmpd** [comment]
Just to be sure, did you clean all caches before flashing the new kernel?. If yes, I'll reopen this issue and keep looking for a fix tomorrow

**Comment by rufoa** [comment]
Yes I did clear the caches - just reflashed now to confirm

**Comment by bitrvmpd** [comment]
Sorry for the delay, could you test these builds please? 
- [old sources](https://github.com/bitrvmpd/msm-3.18-old-source/releases/download/v3.18.84/Bitrvmpd-Kernel-built-in-wifi.zip) kernel
- [Loup kernel, FPC only.](https://github.com/bitrvmpd/msm-3.18/files/1591885/Bitrvmpd-Loup.Kernel-N-v1.0.0-FPC.zip)
- [Loup kernel, Goodix+FPC](https://github.com/bitrvmpd/msm-3.18/files/1591886/Bitrvmpd-Loup.Kernel-N-v1.0.0.zip)

And tell me if there's any difference

**Comment by rufoa** [comment]
**old sources kernel**
Download link gives me a 404 - perhaps because it has been removed/hidden from the releases page

**Loup kernel, FPC only**
FP sensor does not work
- [dmesg](https://github.com/bitrvmpd/msm-3.18/files/1592291/fpconly_dmesg.txt)
- [logcat](https://github.com/bitrvmpd/msm-3.18/files/1592290/fpconly_logcat.txt)
- getprop output:
   ```
   [goodix.fp.miui.analyse]: [1]
   [persist.sys.fp.goodix]: [0]
   [persist.sys.fp.vendor]: [goodix]
   [ro.boot.fpsensor]: [gdx]
   ```

**Loup kernel, Goodix+FPC**
FP sensor does not work
- [dmesg](https://github.com/bitrvmpd/msm-3.18/files/1592317/both_dmesg.txt)
- [logcat](https://github.com/bitrvmpd/msm-3.18/files/1592311/both_logcat.txt)
- getprop output:
   ```
   [goodix.fp.miui.analyse]: [1]
   [persist.sys.fp.goodix]: [0]
   [persist.sys.fp.vendor]: [goodix]
   [ro.boot.fpsensor]: [gdx]
   ```

**Comment by bitrvmpd** [comment]
ASDF! Derpy me, I'm so sorry, forgot to remove one line in my Anykernel script when i was trying to make it work in a ported oreo ROM like 3 weeks ago =(, in fact this line:

```
replace_line init.qcom.rc "setprop persist.sys.fp.vendor none" "setprop persist.sys.fp.vendor goodix";
```

Please test this and tell me how it goes. I'm doing a full wipe before flashing the ROM and Kernel (Because of the override in ramdisk).

[Bitrvmpd-Loup.Kernel-N-v1.0.1.zip](https://github.com/bitrvmpd/msm-3.18/files/1592424/Bitrvmpd-Loup.Kernel-N-V1.0.1.zip)

Hope this solves the issue :(

**Comment by rufoa** [comment]
> Hope this solves the issue :(

It does!! Thank you so much!

> forgot to remove one line in my Anykernel script 

haha yes that would explain it 😄

**Comment by bitrvmpd** [comment]
Awesome! Finally we can close this issue, thank you for your help!
