### ISSUE TITLE
Dynamic Voltage control

### ISSUE THREAD

**Issue by mostafa-z** [Loup-ROM/msm-3.18#23]
Hi man
again thanks for your work 
does this soc needs voltage control? or does it have DVFS because i dont find it !
since it accept much undervolting like from 1150 mv to 600 mv in userspace so far.
it doesn't to be normal but if so how many it can handle and where to find it?
i've found floor and ceiling 1150 ~ 1350 and step 5
regards

**Comment by bitrvmpd** [comment]
Hello!, I'm not familiar with voltage modding, but what are you looking for i guess it's here:
https://github.com/bitrvmpd/msm-3.18/blob/1052cbd12e0c3b70fb752ec07d130c3357f56e7f/arch/arm/boot/dts/qcom/msm8937-regulator.dtsi#L364

https://github.com/bitrvmpd/msm-3.18/blob/1052cbd12e0c3b70fb752ec07d130c3357f56e7f/arch/arm/boot/dts/qcom/msm8937-regulator.dtsi#L365

https://github.com/bitrvmpd/msm-3.18/blob/1052cbd12e0c3b70fb752ec07d130c3357f56e7f/arch/arm/boot/dts/qcom/msm8937-regulator.dtsi#L387

https://github.com/bitrvmpd/msm-3.18/blob/1052cbd12e0c3b70fb752ec07d130c3357f56e7f/arch/arm/boot/dts/qcom/msm8937-regulator.dtsi#L398

https://github.com/bitrvmpd/msm-3.18/blob/1052cbd12e0c3b70fb752ec07d130c3357f56e7f/arch/arm/boot/dts/qcom/msm8937-regulator.dtsi#L399

Also you can check [LuizPauloDamaceno's](https://github.com/LuizPauloDamaceno/msm-3.18/commits/rel/msm-3.18-oreo/arch/arm/boot/dts/qcom) work as a guide.

**Comment by mostafa-z** [comment]
thank you very much
