### ISSUE TITLE
Can't compile with HCI USB driver

### ISSUE THREAD

**Issue by nkrapivin** [Loup-ROM/msm-3.18#24]
drivers/built-in.o: In function `btusb_probe':
sensors_ssc.c:(.text+0x6bad58): undefined reference to `get_rome_version'
sensors_ssc.c:(.text+0x6bad58): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `get_rome_version'
sensors_ssc.c:(.text+0x6bae90): undefined reference to `rome_download'
sensors_ssc.c:(.text+0x6bae90): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `rome_download'
drivers/built-in.o: In function `btusb_pm_notify':
sensors_ssc.c:(.text+0x6bafc8): undefined reference to `btusb_pm_sem'
sensors_ssc.c:(.text+0x6bafc8): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against undefined symbol `btusb_pm_sem'
sensors_ssc.c:(.text+0x6bafcc): undefined reference to `btusb_pm_sem'
sensors_ssc.c:(.text+0x6bb00c): undefined reference to `btusb_pm_sem'
sensors_ssc.c:(.text+0x6bb00c): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against undefined symbol `btusb_pm_sem'
sensors_ssc.c:(.text+0x6bb010): undefined reference to `btusb_pm_sem'
drivers/built-in.o: In function `btusb_driver_exit':
sensors_ssc.c:(.exit.text+0x3be0): undefined reference to `btusb_pm_sem'
sensors_ssc.c:(.exit.text+0x3be0): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against undefined symbol `btusb_pm_sem'
drivers/built-in.o:sensors_ssc.c:(.exit.text+0x3be4): more undefined references to `btusb_pm_sem' follow
Makefile:959: ошибка выполнения рецепта для цели «vmlinux»
make: *** [vmlinux] Error 1

**Comment by bitrvmpd** [comment]
Add more info (toolchain, defconfig used, etc) or i'll close this.

**Comment by bitrvmpd** [comment]
`get_rome_version`, `btusb_pm_sem` and `rome_download` are defined here https://github.com/bitrvmpd/msm-3.18/blob/1052cbd12e0c3b70fb752ec07d130c3357f56e7f/drivers/bluetooth/ath3k.c#L370

Checking the Makefile, this flag is needed to include ath3k.c
https://github.com/bitrvmpd/msm-3.18/blob/1052cbd12e0c3b70fb752ec07d130c3357f56e7f/drivers/bluetooth/Makefile#L18
```
CONFIG_BT_ATH3K=y
```

#### Location
Networking support -> Bluetooth subsystem support -> Bluetooth device drivers  -> Atheros firmware download driver (Enable this)

I tested it, and compiles w/o issues.

**Comment by nkrapivin** [comment]
Toolchain UberTC master branch
OS lubuntu 17.10.1
WOW! THX, IT'S WORKED!
