### ISSUE TITLE
How to make WiFi work？

### ISSUE THREAD

**Issue by imzf** [Loup-ROM/msm-3.18#25]
Hello I compiled a kernel, working on AOSP, WiFi. But on MIUI, WiFi doesn't work. Please tell me what to do to make the kernel's WiFi drive work on MIUI

**Comment by mostafa-z** [comment]
hi
* some changes needs in your config for miui
CONFIG_MODULES=y
CONFIG_WIL6210=m
CONFIG_PRONTO_WLAN=m
"m" stands for module.
but this wifi config doesn't work for aosp!
* to make wifi working in miui you need one more step
mv /system/lib/modules/wlan.ko /system/lib/modules/pronto/pronto_wlan.ko
* wchich means move wlan.ko module to pronto directory and replace/rename with pronto_wlan.ko
*.ko files are conpiled drivers as module
they called by "insmod *.ko" or "modprobe *.ko" from rc files which miui do them for you.
* i don't think compiled modules from an upsreamed kernel can load on stock kernel "3.18.31". so try compile them each time you compile the whole kernel source.
ps: you can compile drivers as module and load them when you need them like cpu governors, network drivers, etc

**Comment by imzf** [comment]
@mostafa-z Thank you very much, sir, for taking the time to answer the question for me.

> i don't think compiled modules from an upsreamed kernel can load on stock kernel "3.18.31". so try compile them each time you compile the whole kernel source.
ps: you can compile drivers as module and load them when you need them like cpu governors, network drivers

I'm not very clear about this. Can you specify the steps? Or, for example, I'll refer to it.
In the end, thank you again for your help.

**Comment by mostafa-z** [comment]
@imzf
1-if you compiled module within a 3.18.32 kernel source thus module wont load on a system which has been booted with 3.18.31. i think different kernel version will lead it to mismatch state.
2-CONFIG_CPU_FREQ_GOV_CONSERVATIVE=m
it will build this governor as a module then you can load it when you need it with "insmode /system/lib/modules/conservative.ko. in this case you can save kernel image size.
don't do this with system drivers or default drivers unless you loaded them in rc files.

**Comment by bitrvmpd** [comment]
Thanks @mostafa-z for the reply!

**Comment by imzf** [comment]
@bitrvmpd In miui china if i use Loup.Kernel-v3.18.93-N-20180203-wifi.zip button flashlight in notification bar can not enable. But i can fix with application
And Hotspot is not working ， can be connected, but it can't connect to the Internet

**Comment by imzf** [comment]
@mostafa-z @bitrvmpd Why is the wlan.ko that I compiled is so big? 80.2mb. You compiled the WLAN. Ko only 6MB
![image](https://user-images.githubusercontent.com/3401994/38002646-1882074a-3266-11e8-8d29-3521072c0e15.png)

**Comment by bitrvmpd** [comment]
- **wlan.ko size**: check this https://github.com/bitrvmpd/msm-3.18/pull/12

Wifi hotspot and led flash light may need something else to work in MIUI, can you provide dmesg/logcat logs ?

**Comment by imzf** [comment]
@bitrvmpd 
[Loup.Kernel-v3.18.93-N-20180203-wifi.log](https://github.com/bitrvmpd/msm-3.18/files/1854408/Loup.Kernel-v3.18.93-N-20180203-wifi.log)

**Comment by imzf** [comment]
@bitrvmpd 

> 
    wlan.ko size: check this #12
is work，thank you

**Comment by mostafa-z** [comment]
@imzf 
Anyway if you are trying to reduce any other module size this can help to reduce it too
android-toolchain/bin/arm-eabi-strip --strip-unneeded /modules/* 2>/dev/null
android-toolchain/bin/arm-eabi-strip --strip-debug /modules/* 2>/dev/null

**Comment by imzf** [comment]
@mostafa-z Now, sir, WiFi is working. But I have one problems now. Hotspot is not working, can be connected, but it can't connect to. Opening Hotspot will cause the mobile data connection to be unworking, can't connect to the Internet, and the phone must be restarted.
Can you tell me how to solve this problems? (I'm sorry, I'm not good at English, the translation software used)
