### ISSUE TITLE
MTP issue with this kernel and its fork

### ISSUE THREAD

**Issue by celeron633** [Loup-ROM/msm-3.18#28]
I found a issue with the kernel:

1. I can use MTP to transfer files from PC to phone, but I can't transfer a large file from Phone to PC.
2. Tiny files are okay, only happen when a large file was transferred.
3. this kernel and other forks or releases such as Clarity all have this issue.
4. kmsg says: [  262.687499] msm_hsusb msm_hsusb: [ep_queue] Larger req is supported only for Bulk OUT.
5. But I just searched some documents and I found when the Responder(phone) transfer files to the Initiator(PC), it will surely use Bulk out method.
6. Is this a android hal issue or not related to kernel ?

Hope a fix or a solution out ^_^.

![screenshot from 2018-08-26 22-26-17](https://user-images.githubusercontent.com/23251507/44637405-88a53980-a9e3-11e8-80e8-126d415f4e25.png)
![screenshot from 2018-08-26 22-26-59](https://user-images.githubusercontent.com/23251507/44637409-935fce80-a9e3-11e8-9933-1aa250794ab4.png)
![screenshot from 2018-08-26 22-28-36](https://user-images.githubusercontent.com/23251507/44637421-9b1f7300-a9e3-11e8-9dd0-65c6aa68e6a4.png)

**Comment by bitrvmpd** [comment]
Not a kernel issue, the mtp implementation on linux it's kinda broken :nerd_face:  Windows doesn't have this bug. Try using http://whoozle.github.io/android-file-transfer-linux/

**Comment by celeron633** [comment]
Sir, Windows has the same issue. I can't copy or drag any large files out. just didn't give any error message. The logcat and dmesg shows the same error. I found this on Windows at first.

**Comment by bitrvmpd** [comment]
411kB is not "large", so again. check with android-file-transfer

**Comment by celeron633** [comment]
tried and same issue and error log ┌( ಠ_ಠ)┘, btw is this possible due to treble rom? I will compile this zImage with twrp and test.

![screenshot from 2018-08-27 11-57-43](https://user-images.githubusercontent.com/23251507/44639834-9d3bfe80-a9f0-11e8-9de3-5de432729903.png)

**Comment by bitrvmpd** [comment]
Are you using android pie?. Also, my kernel doesn't support treble. But! This totally seems like a ROM issue. Not a kernel problem.

Don't open issues if you're using a GSI.

**Comment by celeron633** [comment]
Nope, not a gsi rom. I built my own rom with lineage oreo source. Actually i am using Gabriel kernel which is a fork of your work, and just need to modify two files to support treble. according to the author of  Gabriel, this happens on non-treble oreo too.
the clarity kernel also had this problem so I am asking for your help if it is a kernel related issue ,,,,
Thanks for your reply, I will check the device tree. lol

**Comment by celeron633** [comment]
Thanks for your correct judgement, Sir!
finally I found it because init.qcom.usb.rc writes a exceed value to mtp_tx_req_len to cause this bug.
Thanks for your hard work on this kernel.
